targets:
  $default:
    builders:
      graphql_codegen:
        options:
          clients:
            - graphql
            - graphql_flutter
          scalars:
            Long:
              type: int
              fromJsonFunctionName: longFromJson
              toJsonFunctionName: longToJson
              import: package:bussit/graphql/scalar.dart

