
query Itinerary(
  $fromPlace: String,
  $toPlace: String,
  $from: InputCoordinates,
  $nResults: Int,
  $time: String,
  $date: String,
  $arriveBy: Boolean,
  $modes: [TransportMode],
){
  plan(
    from: $from,
    fromPlace: $fromPlace,
    toPlace: $toPlace,
    numItineraries: $nResults,
    time: $time,
    date: $date,
    arriveBy: $arriveBy,
    transportModes: $modes,
  ) {
    itineraries {
      walkDistance
      duration
      startTime
      endTime
      waitingTime
      legs {
        realTime
        startTime
        endTime
        mode 
        transitLeg
        rentedBike
        duration
        distance
        serviceDate
        legGeometry {
          points
        }
        intermediatePlaces {
          lat
          lon 
          stop {
            vehicleMode
            gtfsId
          }
          bikeRentalStation {
            bikesAvailable
            stationId
          }
        }
        from {
          name 
          lat
          lon
          stop {
            lat
            lon
            name
            gtfsId
            code
            desc
            zoneId
            vehicleMode
            locationType
            platformCode
          }
          bikeRentalStation {
            bikesAvailable
            stationId
          }
        }
        to {
          name 
          lat
          lon
          stop {
            name
            gtfsId
            lat
            lon
            code
            desc
            zoneId
            vehicleMode
            locationType
            platformCode
          }
          bikeRentalStation {
            bikesAvailable
            stationId
          }
        }
        trip {
          tripHeadsign
          routeShortName 
          gtfsId
        }
      }
    }
  }
}
